services:
  wordpress:
    build: .
    restart: always
    ports:
    - "80:80" # HTTP
    - "443:443" # HTTPS
    - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: "mysite.com"
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_USER: ${DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${DB_NAME:-exampledb}
      WORDPRESS_DEBUG: ${WP_DEBUG:-false}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      CACHE_LOC: ${CACHE_LOC:-/var/www/html/wp-content/cache}
      TTL: ${TTL:-80000}
      PURGE_PATH: ${PURGE_PATH:-/__cache/purge}
      PURGE_KEY: ${PURGE_KEY:-}
      BYPASS_HOME: ${BYPASS_HOME:-false}
      BYPASS_PATH_PREFIXES: ${BYPASS_PATH_PREFIXES:-/wp-admin,wp-includes}
      CACHE_RESPONSE_CODES: ${CACHE_RESPONSE_CODES:-2XX,404,403}
      CADDY_GLOBAL_OPTIONS: |
        email hi@mysite.com
        auto_https disable_redirects
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_SITEURL', 'https://mysite.com');
          define('WP_HOME', 'https://mysite.com');

    volumes:
      - ./app:/var/www/html

    tty: true
